services:
  postgres:
    image: postgres:15
    container_name: github_analyzer_db
    environment:
      POSTGRES_DB: github_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simplepass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: